### PR TITLE
ADAPT-3949: Updated Gatsby to v4, along with dependencies.

### PR DESCRIPTION
**Pull request by nplowman**
# READY FOR REVIEW

# Summary
- Updates Gatsby to v4, along with any required dependencies.

# Review By (Date)
- By end of the sprint, no rush.

# Criticality
- 3/10. Gatsby v4 has some nice new features and faster build times, but otherwise not critical. 

# Review Tasks

## Setup tasks and/or behavior to test
Entire site will need to be reviewed to check for potential regressions introduced by package updates. 

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
This looks good to me. 

@yvonnetangsu please have a quick eyeball of the front end for any irregularities.

**Review by yvonnetangsu — CHANGES_REQUESTED** [review]
@nplowman @sherakama I did find one weirdness with the accordion expand/collapse all buttons
https://deploy-preview-240--giving-dev.netlify.app/faqs/
Screen Shot 2021-12-08 at 12 01 46 PM

I checked the live site and the #239 preview that just got merged, and it appears that those are both ok so likely introduced in this update.

**Comment by yvonnetangsu** [comment]
> @nplowman @sherakama I did find one weirdness with the accordion expand/collapse all buttons https://deploy-preview-240--giving-dev.netlify.app/faqs/ Screen Shot 2021-12-08 at 12 01 46 PM
> 
> I checked the live site and the #239 preview (https://deploy-preview-239--giving-dev.netlify.app/faqs/) that just got merged, and it appears that those are both ok so likely introduced in this update.

I think I know what's causing this. It's probably from updating Decanter 6 to a newer version (was introduced in Caryl's Decanter PR @sherakama). @nplowman If you could please add the SCSS override to fix the buttons, that'd be awesome.

**Comment by sherakama** [comment]
Good catch @yvonnetangsu 

Regarding the update to the Decanter version, do we need to fix anything there or is this an understandable expectation?

**Comment by yvonnetangsu** [comment]
> Good catch @yvonnetangsu
> 
> Regarding the update to the Decanter version, do we need to fix anything there or is this an understandable expectation?

Hmmmm good question.... let me do a little more thinking 🤔

**Comment by sherakama** [comment]
@yvonnetangsu if you know what the CSS fix is for the icon could you chip it into this PR please?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu if you know what the CSS fix is for the icon could you chip it into this PR please?

Sure will do. I'll do a temporary fix here so it's not blocking merge and will think more about what to do with the buttons in Decanter v6.

**Comment by sherakama** [comment]
> Sure will do. I'll do a temporary fix here so it's not blocking merge and will think more about what to do with the buttons in Decanter v6.

Thank you very much.

**Comment by yvonnetangsu** [comment]
@sherakama Accordion buttons have been fixed. I also fixed the buttons fr the red color accordion option (can't find a live page with it, but it should be ok)

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
