### PR TITLE
RELEASE: V2.3.0

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# RELEASE: V2.3.0

### CODE REVIEW

**Review by sherakama — COMMENTED** [review]
FYI: Pushing this through.

**Comment by sherakama** [comment]
Not sure why this punched a major release when it was tagged with minor... 🤷 

Ticket for the backlog I suppose.

**Comment by sherakama** [comment]
@forrestglick & @wmui51 This is out and live now.

**Comment by forrestglick** [comment]
@sherakama @wmui51 Thank you! The push looks good. I've notified the program owner it's live.

**Comment by yvonnetangsu** [comment]
Thanks @sherakama ! 😄

**Pull request merged**
