### PR TITLE
new endowed positions data

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Updated Endowed Positions data

# Review By October 5, 2022
- We would like to push to Prod on Friday, 10/7.

# Criticality - 6
- This is a new data set of endowed positions, so it does not impact any pages beyond the listing of positions.

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. go to /endowed-positions subpages (may have to change the url manually back to local/test env as the homepage takes you to the dev site) 
3. Spot check to see if the pages are working as expected, this is just a data update w/o any functionality changes

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]

**Comment by forrestglick** [comment]
@wmui51 The data set is looking good. Please update the Last updated copy on the sub-pages to say "Last updated October 7, 2022."

**Comment by forrestglick** [comment]
@wmui51 Update looks good. Please push to Dev for final review by the program. Plan is to then push to Prod on Friday (10/7). Thanks!

**Comment by yvonnetangsu** [comment]
> @sherakama Please merge into Dev when you have the chance. It's just a new data set of endowed positions. At some future point, I'd be interested in discussing whether it makes sense to continue to host/serve this json data via this repo, or whether it would be better to upload/serve the json via another method. We anticipate a minimum of 6 data updates per year. Thanks!

Got a notification so I went ahead and merged into `dev`. Hope you don't mind 😃

**Comment by forrestglick** [comment]
Thanks, @yvonnetangsu. I always feel a bad about bugging you all with these simple data updates. Really appreciate the help!

**Comment by yvonnetangsu** [comment]
> Thanks, @yvonnetangsu. I always feel a bad about bugging you all with these simple data updates. Really appreciate the help!

No worries! Minimum 6 data updates (assuming around 10?) per year sounds ok to me - @sherakama what do you think?

**Comment by yvonnetangsu** [comment]
Hi @forrestglick!
@sherakama and I had a quick chat. It's Canadian Thanksgiving long weekend for Shea, but I'm around this Friday so can help with pushing this to prod on 10/7.

**Comment by forrestglick** [comment]
Sounds great @yvonnetangsu. The program has reviewed the content update and approved the changes, so we are good to go for a push tomorrow (10/7). Thanks again for stepping in. And Happy Thanksgiving to Shea!

**Comment by sherakama** [comment]
Thanks @yvonnetangsu

**Pull request merged**
