### PR TITLE
Nojira: Remove stripe javascript and set images to load lazy

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Removes stripe from codebase

### CODE REVIEW

**Comment by sherakama** [comment]
@forrestglick 
@yvonnetangsu 
@buttonwillowsix 

Anyone know of a good reason to keep the stripe script?

**Comment by yvonnetangsu** [comment]
@sherakama I'm curious about this as well. Was this just for testing way back? We might or might not want to remove this as well 🤔 This below file was added long time ago for stripe testing
https://github.com/SU-SWS/ood_giving_site/tree/dev/static/.well-known

**Comment by sherakama** [comment]
I've asked Robert Giedt to confirm that stripe is not needed on this site. Waiting on him to get back from vacation.

**Comment by sherakama** [comment]
Robert can't think of a good reason it needs to stay. I believe we can remove this then.

**Pull request merged**
