### PR TITLE
DS-538: Change label `Medicine + Health Care` to `Medicine`

### PR DESCRIPTION
**Pull request by stfurkan**
# NOT READY FOR REVIEW

# Summary
- Change label `Medicine + Health Care` to `Medicine` - DS-538

# Review By (Date)
- End of sprint

# Criticality
- 4

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to `/areas-to-support`
3. Make sure that the label changed to `Medicine`

## Old

image

## New

image

### CODE REVIEW

**Comment by stfurkan** [comment]
> GTG

Thanks for the quick review @sherakama :) Do we need to change anything else in Storyblok?

**Comment by sherakama** [comment]
https://app.storyblok.com/#/me/spaces/78141/datasources/23507

> > GTG
> 
> Thanks for the quick review @sherakama :) Do we need to change anything else in Storyblok?
> 
> EDIT: I'm merging this. I'll create the release PR and wait for your approval just in case if we need to make any other change in Storyblok.

The label change will work without changing anything in Storyblok, however, there is a label discrepancy between the website and the storyblok form now. I don't think it is hard for the content editor to figure out but you could change it to match. Go into Storyblok, update the field labels, and remove the `+ Healthcare` there on the Area's to support page. 

Both on dev and prod spaces.

cc @yvonnetangsu

**Comment by stfurkan** [comment]
> https://app.storyblok.com/#/me/spaces/78141/datasources/23507
> 
> > > GTG
> > 
> > 
> > Thanks for the quick review @sherakama :) Do we need to change anything else in Storyblok?
> > EDIT: I'm merging this. I'll create the release PR and wait for your approval just in case if we need to make any other change in Storyblok.
> 
> The label change will work without changing anything in Storyblok, however, there is a label discrepancy between the website and the storyblok form now. I don't think it is hard for the content editor to figure out but you could change it to match. Go into Storyblok, update the field labels, and remove the `+ Healthcare` there on the Areas to support page.
> 
> Both on dev and prod spaces.
> 
> cc @yvonnetangsu

Thanks @sherakama :) I updated the field labels in Storyblok. Do I need to click `Publish` too or clicking `Save` is enough for updating the field labels?

image

**Comment by sherakama** [comment]
> Do I need to click Publish too or clicking Save is enough for updating the field labels?

Save and publish is for the content. The field labels should be 'saved' once you change them.

**Pull request merged**
