### PR TITLE
Release V2.1.3

### PR DESCRIPTION
**Pull request by sherakama**
# Release V 2.1.3

* Nojira: Algolia indexing enable
* Nojira: Professorships - Update title text on pages

### CODE REVIEW

**Comment by sherakama** [comment]
Just waiting for the green build lights...

**Review by yvonnetangsu — APPROVED** [review]
GTG! 🚀

**Comment by sherakama** [comment]
> 10:08:40 AM: success index to Algolia - 8.417s - Done!

**Comment by sherakama** [comment]
@forrestglick https://giving.stanford.edu/search-results?page=1&term=professorships

**Pull request merged**
