### PR TITLE
Release v2.2.2

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for review

### CODE REVIEW

**Comment by sherakama** [comment]
@forrestglick @wmui51 @yvonnetangsu FYI

**Comment by sherakama** [comment]
@yvonnetangsu & @wmui51 Is this ok to go out?

**Comment by forrestglick** [comment]
Yes, GTG @sherakama. We have review and approval of the Endowed Positions updates.

**Comment by sherakama** [comment]
Any production Storyblok changes that need to happen before code merge?

**Comment by forrestglick** [comment]
I will add the new Search component to the Endowed Positions landing page via Storyblok once the code is merged. It's initial absence should not present any issues. The sub-pages update will be good to go after code merge.

**Comment by sherakama** [comment]
Ok, here we go.

**Pull request merged**
