### PR TITLE
Release/v4.2.2

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #454 

# Review By (Date)
- Nov 12 morning

# Criticality
- 6

# Review Tasks

## Setup tasks and/or behavior to test

1. #454

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@forrestglick Release is up

**Comment by yvonnetangsu** [comment]
@forrestglick @sherakama Pushing this to PROD client would like it live this morning

**Comment by yvonnetangsu** [comment]
@forrestglick Changes are live:
https://giving.stanford.edu/endowed-positions/bass-university-fellows-in-undergraduate-education-program/

**Comment by forrestglick** [comment]
Thanks @yvonnetangsu – All looks great! I notified the client, and she is very pleased. I also updated the link on the Storyblok /endowed-positions page to reflect the new libraries link and set-up a redirect, just in case there are links from outside pages. Appreciate your help with the push!

**Comment by yvonnetangsu** [comment]
> Thanks @yvonnetangsu – All looks great! I notified the client, and she is very pleased. I also updated the link on the Storyblok /endowed-positions page to reflect the new libraries link and set-up a redirect, just in case there are links from outside pages. Appreciate your help with the push!

Great - I'm glad everything is working as expected @forrestglick ! 😄

**Pull request merged**
