### PR TITLE
update Woods Institute link

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Update to a broken link on the Woods Institute Endowed Positions page

# Review By April 15
- This is not urgent by any stretch, but nice to get done

# Criticality - 2
- This does not affect any other part of the website.

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to the Woods Institute page:/endowed-positions/stanford-woods-institute-for-the-environment
3. Verify the link in the descriptive text points to: https://woods.stanford.edu/people

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
LG2M. Let me know when you'd like to move it along.

**Comment by forrestglick** [comment]
This looks good to me – Please merge into Dev. Thank you, @sherakama

**Comment by forrestglick** [comment]
The update has been reviewed on Dev and looks good to push to Prod. Thanks, everyone!

**Comment by yvonnetangsu** [comment]
@sherakama I can take care of this release 🤠

**Comment by sherakama** [comment]
Thanks @yvonnetangsu

**Pull request merged**
