### PR TITLE
Release/v4.2.0

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Allow for multiple countdowns
- Updated endowed positions list

# Review By (Date)
- End of the week

# Criticality
- Normal

### CODE REVIEW

**Review by wmui51 — APPROVED** [review]
lgtm, looks like the countdown updates will go live, and that was working as expected when i tested, so should be good to go.

**Comment by wmui51** [comment]
@sherakama yup, I will update the component options on the prod Storyblok build to match that of dev when this is released.

**Review by yvonnetangsu — APPROVED** [review]
Thank you for confirming that the countdown is production ready too @wmui51! GTG @sherakama 🚀

**Comment by sherakama** [comment]
Thanks @wmui51 and @yvonnetangsu

**Comment by wmui51** [comment]
component in prod Storyblok is configured to match the fields that are on dev.

**Comment by sherakama** [comment]
Thank you @wmui51

**Pull request merged**
