### PR TITLE
NoJira | @wmui51 | Feat/countdown hours only view

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Added logic to `Countdown` component for the option to countdown in HH:MM:SS instead of just DD:HH:MM:SS
- Wrapped the `Countdown` component with `SbEditable` so it can be configured via Storyblok
- Added the following blok props: `hasDays` (sets whether or not to show days countdown ring), `date` (uses the Storyblok datepicker to countdown to selected date/time), and `hourPieRange` (sets the max amount of countdown hours when `hasDays` is false to properly decrement the hours countdown pie.
- Added temporary default countdown time so the current campaign using the `Countdown` component will not break

# Review By March 11
- This version of the countdown timer (36-hour) will be used on April 4, but we'd like to have the page built out by by the third week in March.

# Criticality - 6
- The Athletics team requires the countdown timer as part of their marketing and promotional efforts.
- We need to ensure that this update does not impact the existing countdown timer deployed to Prod at: https://giving.stanford.edu/athletics-giving-day/ 

# Review Tasks

## Setup tasks and/or behavior to test

@sherakama @yvonnetangsu I am not sure how to test this without merging to `dev` and pushing it to the dev Storyblok instance. I have tested this by pointing Storyblok to my local.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by wmui51** [comment]
@forrestglick  here are some screenshots

Default state for current campaign
image

Date picked via Storyblok along with other new options
image

New empty state w/o Days countdown ring
image

**Review by sherakama — APPROVED** [review]
Looks fine to me. 

You can add more 'preview urls' in Storyblok for pull requests but local works too!

**Comment by forrestglick** [comment]
This looks good to me, but will need to review it via Dev to fully evaluate. As I noted in the summary above, I want to confirm that this update (once pushed to Prod) will not break the existing implementation at: https://giving.stanford.edu/athletics-giving-day/

**Comment by sherakama** [comment]
Merging to dev

**Comment by forrestglick** [comment]
@wmui51 In looking at the SB component on Dev, I see the field: "Maximum amount of hours w/o days counter" and an integer field. Can you please help me to understand how this is used? When I set the limit to say "36", the counter is displaying a much larger integer ("700").

**Comment by wmui51** [comment]
@forrestglick that's used to show what the hours pie should be divided by so that it removes the proper fraction each hour that goes by, so if you have 36 set it should take away 1/36th of a section with each hour. That is needed because ordinarily we would count down 24 hours, but since we can countdown any number of hours now we need to know each 1/x of the pie to decrement, I made it to be set by the user so we can do 36, 48, 72, hours etc.

In your example it does not really work since there are more hours than the pie max you put. To test this out you can set the clock to a 2 day countdown via the date field and then try setting the pie max to 72, then we should see about 2/3 of the pie has been counted down.

**Comment by forrestglick** [comment]
Thanks for the clarification @wmui51 – I now understand how it works. I might suggest we change the label to something like: "Total number of hour segments". Open to better suggestions :) And is it possible to utilize Pacific Time instead of the GMT time?

**Comment by wmui51** [comment]
@forrestglick we can change the label when we get this into prod, that's no problem. As for using PT instead of GMT, not sure that's possible as that's the date picker that Storyblok provides, it felt like the easiest way for users to pick a countdown to date.

**Comment by forrestglick** [comment]
@wmui51 thanks for addressing my questions above. I'm good with your approach. Will pushing this to Prod have any impact on the existing countdown timer on the ATH Giving Day page? If you feel confident it will not, I'm good with the push to Prod.

**Comment by forrestglick** [comment]
@wmui51 I added a second instance of the timer to the [Dev page](https://app.storyblok.com/#/me/spaces/122401/stories/0/0/132120300/blok/17ac9f22-8a5c-4279-bc58-22211e80133d) and it worked as expected by pulling the default date corresponding to our campaign start. However, when I tried to publish the page, I got an error saying the "field countdown.hasDays can't be blank". I need the "Has days" option to be set to false for the first instance of the timer. Please investigate the error. Thanks!
timer_dev_publish

**Comment by wmui51** [comment]
Will do, but what is the page your are testing on? That should be `false` by default so wondering why that error shows.

**Comment by wmui51** [comment]
@forrestglick i actually just tried dropping a Countdown to the page w/o any Storyblok options and it saved, you can see it on the current page.

**Comment by forrestglick** [comment]
@wmui51 The Endowed Positions test page on Dev includes the two timer instances. The top instance is the "no days" timer and the bottom of the page includes an instance with days. I'm assuming the top instance is causing the error when trying to publish.

**Comment by wmui51** [comment]
@forrestglick I think that was a result of one of the instances using an old configuration. I just removed them and added two new ones and they published, let me know if it works for you.

**Comment by forrestglick** [comment]
@wmui51 Previously, making changes to the number of hour segments and end-time was immediately reflected in the WYSIWYG interface. That's no longer happening for me. I think something is still amiss.

**Comment by wmui51** [comment]
@forrestglick were the ones you were editing the ones I placed in there or new ones you put in? I am trying to see if maybe it was instances that were tied to my local testing.

For me, it has always been the case that when I set a time that I had to save and refresh before seeing updates. I will check again for the max hours field.

**Pull request merged**
