### PR TITLE
Feat/storyblok time configuration

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Making the Countdown component date configurable via storyblok
- Also adding a Storyblok option to set the total days of a campaign and removed the hardcoded 29 days from previous campaign

# Review By (Date)
- When does this need to be reviewed by?
- I don't think there is a rush, but @forrestglick could provide more input.

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Go to this page: https://app.storyblok.com/#/me/spaces/122401/stories/0/0/397282734/blok/4397e5fc-f1d4-4a4e-9da3-fcca0dcc4c07, or any Storyblok page on dev and test adding a Countdown.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by wmui51** [comment]
@sherakama it looks like the linter is failing to run because of the Node version?

**Comment by wmui51** [comment]
@sherakama i was wondering if the server that hosts the site is always on PST/PDT? and if so and i run a `new Date()` that would be based on the server's clock?

**Comment by sherakama** [comment]
> @sherakama i was wondering if the server that hosts the site is always on PST/PDT? and if so and i run a `new Date()` that would be based on the server's clock?

@wmui51 
This is a very much all depends. 

The first thing that runs the code is the CI/CD build and that server runs somewhere but I don't know where. 

After the code gets rendered and shipped it is put on a CDN or multiple servers all over the world. The front end, or after hydrate, code will run based off of the end-user's timezone. 

You can find out what the offset is by 

```
var offset = new Date().getTimezoneOffset();
```

**Comment by wmui51** [comment]
@sherakama i am currently getting the offset with that method, but because the date is based on the end-user's timezone, i am also getting the time difference between the user's timezone and the countdowns which will usually be PT. the issue i'm trying to figure out now is accounting for daylight savings time and then adjusting the PT offset to that. I did not want to install a library like `moment` just for this, so I'll probably make this a prop coming back from Storyblok then. Let me know if you have any suggestions as well, thanks.

**Comment by sherakama** [comment]
> @sherakama i am currently getting the offset with that method, but because the date is based on the end-user's timezone, i am also getting the time difference between the user's timezone and the countdowns which will usually be PT. the issue i'm trying to figure out now is accounting for daylight savings time and then adjusting the PT offset to that. I did not want to install a library like `moment` just for this, so I'll probably make this a prop coming back from Storyblok then. Let me know if you have any suggestions as well, thanks.

Date/time math is one of my least favorite things to do. I highly recommend using a library for this. Moment is great and we've also used https://moment.github.io/luxon/ on other projects in this space.

If you haven't seen [this video](https://www.youtube.com/watch?v=-5wpm-gesOY&themeRefresh=1) you should take a few moments and enjoy it today.

Pass the target time as a prop to your component and then use a library to do the math on browser. That should do it.

**Comment by wmui51** [comment]
@sherakama thanks for the input, if you don't mind me adding a library to this site, I would much rather go that route.

**Comment by sherakama** [comment]
> @sherakama thanks for the input, if you don't mind me adding a library to this site, I would much rather go that route.

Yeah, go for it.

**Comment by wmui51** [comment]
@sherakama I think this is ready to be reviewed and merged into my other feature branch. I have decided to go w/o Luxon for now as that would be a bit of a refactor for all the time stuff. I can do that as well if that is preferred, but this was tested and seems to countdown to the same time regardless of the timezone of the end user. Wanted to get this merged into the feature branch so @forrestglick can test all the changes of the Countdown together.

**Comment by sherakama** [comment]
Ok, I'll merge down into the other branch for testing.

**Pull request merged**
