### PR TITLE
ADAPT-2726: Auto and manual focal point

### PR DESCRIPTION
**Pull request by Lyafel**
# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by Lyafel** [comment]
Reopening per request: https://stanfordits.atlassian.net/browse/ADAPT-2726?focusedCommentId=114256

**Comment by yvonnetangsu** [comment]
@Lyafel We have a new workflow on Giving now. For any new PRs, we'll set the base branch to dev instead of main.

**Comment by yvonnetangsu** [comment]
> Looks good to me. @yvonnetangsu final review?

I think I need to play around with this some more. When I was working on Travel/Study, I find that the focal point only works if the crop has a known image width and height, and not if you only set a width with an auto height.

**Review by yvonnetangsu — COMMENTED** [review]
@Lyafel , @sherakama and I had a chat today and it looks like this might be a little bit more involved than we originally had planned, so we might be putting this work on hold for the time being. Thank you for your work on this.

**Comment by yvonnetangsu** [comment]
Closing this as discussed for now. We can reopen in the future if needed.

**Pull request closed without merging**
