### PR TITLE
Release v3.0.1

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #300 
- #301 
- #302 
- #303 
- #304 
- #306

# Associated Issues and/or People
- ADAPT-5488

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
GTG

**Comment by yvonnetangsu** [comment]
@sherakama I'm going to go ahead and merge since the positions update says last updated Nov 14 😄 Thanks for the super fast review!

**Comment by yvonnetangsu** [comment]
@sherakama Looks like it did what it did to you last time.....I added a patch label but it became a major release 😬

**Comment by sherakama** [comment]
Oi. 

I'll create that ticket now...

**Comment by yvonnetangsu** [comment]
Thanks Shea! It's all working though so at least that's good 😄

**Comment by sherakama** [comment]
https://stanfordits.atlassian.net/browse/ADAPT-5495

**Comment by yvonnetangsu** [comment]
@wmui51 @forrestglick The positions update have been included in this release #301

**Comment by forrestglick** [comment]
I heard back from the program, and they have approved the release of the updated Endowed Positions. Please let me know when it's pushed to Prod. Thanks!

**Comment by yvonnetangsu** [comment]
> I heard back from the program, and they have approved the release of the updated Endowed Positions. Please let me know when it's pushed to Prod. Thanks!

Hi @forrestglick It's been pushed to PROD 👍🏼 😄

**Pull request merged**
