### PR TITLE
NoJira: Style the endowed positions search component

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Added styling to the endowed-positions search component to be added to the main page. Also added a label for accessibility.
image

# Review By Sept 20, 2022
- Hoping to get this all pushed to prod by the end of the month. We will need a few days time for review by the Donor Relations team.

# Criticality 5
- This update only impacts the endowed positions site content and helps to address a usability issue with the current interface–namely users were confused about the scope of the search.

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Check the component in Storyblok via localhost
3. This component already exists but is unstyled and functionality can be checked here:
https://dev.giving.stanford.edu/endowed-positions/
4. Confirm search input is rendering and run a search to test results are being returned.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by forrestglick** [comment]
@wmui51 This is looking good. I had Donor Relations review the updates, and they asked that the search box extended to be longer. Could we double the width/characters displayed?

**Comment by forrestglick** [comment]
Hi @yvonnetangsu – As you know, Wilbert and I have been working on adding a search for the endowed positions as a storyblok component. Thanks again for all your help and guidance in the process! We are now working on styling the component based on feedback from our Donor Relations colleagues. We were asked to remove the redundant "label" for the search box, which was previously an H2 element in the page section. When I removed the optional copy and header spacing was set to none, the white background disappeared and displayed an undesirable gray background. I had to set a vertical spacing of extra-small to get it to render white, but this is still too much vertical space. Any recommendations on how best to tighten up the spacing?
endowed_vertical_spacing

**Comment by yvonnetangsu** [comment]
Hi @forrestglick! Let me take a look at this test page on Storyblok and see if we have a workaround 😄

**Comment by yvonnetangsu** [comment]
@forrestglick I believe I got it to look like what you described now. The trick is to check the "Make title and intro screen reader only" checkbox under the 1st tab in the Section component 😄 (at the bottom of the screenshot)
Screen Shot 2022-09-16 at 3 31 03 PM

This is what the page looks like after this update:

Screen Shot 2022-09-16 at 3 33 13 PM

**Comment by forrestglick** [comment]
@yvonnetangsu Yes! That is what I was trying to achieve. Thanks for the guidance. Submitting the PR for review/approval to push to Dev.

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
