### PR TITLE
ADAPT-5851 | Improve site search a11y

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- A11y improvements for search

# Review By (Date)
- Aug 23 ish?

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at the preview and test the search feature. Make sure that it doesn't break existing functionality.
2. Look at code and see the changes

### CODE REVIEW

**Comment by sherakama** [comment]
Amazing. Thanks @yvonnetangsu

**Comment by yvonnetangsu** [comment]
SODA form has been filled out. I put in a "due" date of August 18 🤷🏼‍♀️ since this is not super urgent.

**Comment by sherakama** [comment]
@yvonnetangsu did you get SODA feedback?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu did you get SODA feedback?

@sherakama Your timing is uncanny. I just received the feedback from SODA 20 minutes ago, and was just about to update the ticket 😆

**Comment by sherakama** [comment]
Spidey

**Comment by yvonnetangsu** [comment]
@sherakama Looks like the work here improves a11y, but there's still remaining work to be done per the SODA results. Are you ok with merging this PR into d`ev`? I'll open a separate PR to address the SODA comments.

**Review by sherakama — APPROVED** [review]
Looks good to me. Thank you!

**Comment by yvonnetangsu** [comment]
Thank you for the review @sherakama! Merging this into dev, then I'll tackle the new batch of SODA feedback 😄

**Pull request merged**
