### PR TITLE
Support redirects from Professorships site

### PR DESCRIPTION
**Pull request by forrestglick**
# READY FOR REVIEW

# Summary
The legacy D7 site: professorships.stanford.edu is being redirected to giving.stanford.edu/endowed-positions which is working well, but redirects to the "sub-pages" are breaking due to the D7 site using spaces in the urls. See http://professorships.stanford.edu/content/Wu%20Tsai%20Neurosciences%20Institute as an example. The proposed dynamic redirect is intended to catch all traffic redirected from the legacy urls and direct users to the top-level landing page for the Endowed Positions content at /endowed-positions.

# Review By June 29, 2022

# Criticality 9
- Links to the legacy Professorships sub-pages are returning 404s on the Giving Site

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to https://professorships.stanford.edu/content/Stanford%20Medicine
3. Verify the redirect lands on /endowed-positions

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by forrestglick** [comment]
@sherakama Could you please let me know if this is a viable/best approach to redirecting the traffic. Thanks!

**Comment by sherakama** [comment]
Seems to work for me: https://deploy-preview-253--adapt-giving.netlify.app/endowed-positions/content/thing

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
However, it looks like you might need to redirect everything from `/content/*` to `/endowed-positions` which would work as long as you never have content put into a folder in Storyblok called `content`

**Comment by forrestglick** [comment]
> However, it looks like you might need to redirect everything from `/content/*` to `/endowed-positions` which would work as long as you never have content put into a folder in Storyblok called `content`

@sherakama So are you suggesting I would modify the redirect to be:
`/content/*   /endowed-positions   301` ? Isn't that overly broad when it's only the legacy links hitting '/endowed-positions/content/' that we need to address?

**Comment by sherakama** [comment]
> @sherakama So are you suggesting I would modify the redirect to be:
/content/* /endowed-positions 301 ? Isn't that overly broad when it's only the legacy links hitting '/endowed-positions/content/' that we need to address?

It is overly broad but I was looking at your example link: `http://professorships.stanford.edu/content/Wu%20Tsai%20Neurosciences%20Institute`

Redirects start after the domain name so your redirect path would look like `/content/Wu%20Tsai%20Neurosciences%20Institute`

Ah, it looks like you have a redirect from `http://professorships.stanford.edu/*` -> `https://giving.stanford.edu/endowed-positions/:splat` in the vanity URL tool. Ok. You can ignore my comment about changing it to `/content`

**Pull request merged**
