### PR TITLE
Release/v4.0.3

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #321 

# Review By (Date)
- Dec 19 Monday

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at code diff and preview

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
GTG

**Comment by yvonnetangsu** [comment]
> GTG

Thank you @sherakama !

**Comment by yvonnetangsu** [comment]
@forrestglick @wmui51 
Dec 19 updates are live
https://giving.stanford.edu/endowed-positions/graduate-school-of-business/

**Comment by forrestglick** [comment]
Thanks @yvonnetangsu. It looks great! Sending the good news to the program lead. Have a wonderful winter break!

**Comment by yvonnetangsu** [comment]
> Thanks @yvonnetangsu. It looks great! Sending the good news to the program lead. Have a wonderful winter break!

You too, @forrestglick ! Happy Holidays to you and your family and have an awesome break 😄 🎉

**Pull request merged**
