### PR TITLE
New endowed positions dataset

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Update to Endowed Positions data

# Review By Sept 5, 2023
- We would like to push this update live on Sept 5, with a review by the client via Dev

# Criticality - 4
- This is an update to the data and does not affect other parts of the Giving site.
 
# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Endowed positions pages and click on a few centers/schools to confirm rendering of results
3. Verify the latest update date in the footer states Sept 5

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
> @forrestglick can you edit the details for when this should be reviewed and deployed?

I believe Forrest is out - I'll check back early next week (after Labor Day) :)

**Comment by forrestglick** [comment]
Hi @yvonnetangsu, I returned from vacation last evening :) The client would like to push live on Tuesday, Sept 5 after a quick review on Dev to confirm the updates look as intended. Thank you!

**Review by yvonnetangsu — APPROVED** [review]
GTG!
Merging this into `dev` @forrestglick

**Comment by yvonnetangsu** [comment]
Have a great weekend @forrestglick 😄 `dev` should be ready for client review - we'll cut a release on Tuesday.

**Pull request merged**
