### PR TITLE
Release/v4.0.10

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW (to go live on Oct 19)

# Summary
- #381 
- #380 

# Review By (Date)
- by 10/18

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at the code diff

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama Rebecca's #380 is included here too - you have already reviewed so I'm going to assume it's GTG in this release.

**Comment by yvonnetangsu** [comment]
@forrestglick Release PR is prepped and we won't merge till Oct 19

**Review by sherakama — APPROVED** [review]
GTG

**Comment by yvonnetangsu** [comment]
@rebeccahongsf Including this in the release - FYI 😄

**Comment by yvonnetangsu** [comment]
Confirmed with @forrestglick in meeting today that we'll merge this later near the end of the day (probably around 4:30pm PT before I go to my Bewell appointment) cc @sherakama

**Comment by forrestglick** [comment]
Update looks great! Thank you.

**Pull request merged**
