### PR TITLE
Release: v4.0.4

### PR DESCRIPTION
**Pull request by sherakama**
# Release: v4.0.4

# Summary
- Update release.yml
- NoJira: Protect Dev. 
- New endowed positions data

### CODE REVIEW

**Comment by sherakama** [comment]
cc @forrestglick & @wmui51

**Review by yvonnetangsu — APPROVED** [review]
LGTM - thank you @sherakama ! 🎉

**Comment by forrestglick** [comment]
@yvonnetangsu @sherakama I think this merge into Prod is still blocked?

**Comment by yvonnetangsu** [comment]
Hi @forrestglick 👋🏼  - @sherakama and I were both at webcamp. Sorry about the delay. Looks like Shea beat me to the merging already and your changes are now on PROD.

**Comment by forrestglick** [comment]
Yes, thank you @yvonnetangsu and @sherakama. I just ran a build of the site and sent confirmation to the client. Really appreciate your help and sorry to have missed Shea's RFC Webcamp presentation. I'll need to watch the recording :)

**Pull request merged**
