### PR TITLE
update endowed positions dataset

### PR DESCRIPTION
**Pull request by wmui51**
# READY FOR REVIEW

# Summary
- Update to Endowed Positions data

# Review By November 7, 2022
- We would like to push to production on Monday, November 7, if possible

# Criticality - 4
- This update only affects the endowed positions data.

# Review Tasks

## Setup tasks and/or behavior to test

1. Go to site and make sure the site still works, I think the stakeholders will check the preview link to make sure the data is correct.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by forrestglick** [comment]
@wmui51 This data update looks good. I've set @sherakama as a reviewer. Once pushed to Dev, I'll have the program take a quick look to confirm the content. Optimally, pushing through to Prod later today.

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
@forrestglick You can review on dev now.

**Comment by forrestglick** [comment]
Thanks @sherakama! I've sent the Dev link to the client for (content) review.

**Comment by forrestglick** [comment]
@sherakama The client has reviewed and approved the update. Please push to Prod. Thanks!

**Pull request merged**
