### PR TITLE
Release/v4.0.5

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #347 
- #348 
- #354 

# Review By (Date)
- Jul 11

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at preview and code

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama Prepping this for tomorrow (to be merged July 11)
cc @forrestglick

**Comment by yvonnetangsu** [comment]
Added @wmui51's global footer fix into this as well. You can see the global footer on the search results page eg, here:
https://deploy-preview-353--adapt-giving.netlify.app/endowed-positions/search?term=smith
And the links to the school page records
https://deploy-preview-353--adapt-giving.netlify.app/endowed-positions/graduate-school-of-business/

**Comment by forrestglick** [comment]
@yvonnetangsu – thanks for adding the global footer component into this release. All looks good to push, @sherakama.

**Comment by yvonnetangsu** [comment]
Closing in favor of #356

**Pull request closed without merging**
